name: Monthly OA-ratios run
on:
  schedule:
    - cron:  '0 3 1 * *'      # 03:00 UTC on the 1st
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with: { python-version: "3.12" }

    - name: Install package
      run: |
        python -m pip install -U pip
        pip install -e .

    - name: Collect CSV
      run: python -m paywallfail.data            # ← calls oa_ratios.collect:main

    - name: Make PDF plot
      run: python -m paywallfail.plot               # ← calls oa_ratios.plot:main

    - name: Move outputs to directory
      run: |
        mkdir -p output
        mv OSvsNOA.pdf OSvsNOA.png data.csv output/
          
    - name: Get today's date
      id: date
      run: echo "today=$(date -u +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

    - name: Commit plots to repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add output/
        git commit -m "Update monthly plot - ${{ steps.date.outputs.today }}" || echo "No changes"
        git push
        
    - uses: actions/upload-artifact@v4
      with:
        name: oa-ratios-${{ github.run_id }}
        path: output/*

    - name: Release with artefacts
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest-monthly
        name: OA vs NOA ratios ${{ steps.date.outputs.today }}
        files: output/*
        prerelease: false
        make_latest: true
